
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class jfrmEjercicioGA3 extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmEjercicioGA3() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(900,800);
        this.setTitle("Partes del ordenador");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jlblnompieza = new javax.swing.JLabel();
        jlblpieza = new javax.swing.JLabel();
        jlbldescripcion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 750));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 800));

        jlblnompieza.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jlblnompieza.setForeground(new java.awt.Color(255, 153, 0));
        jlblnompieza.setText("Partes del Ordenador");

        jlblpieza.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlblpieza.setForeground(new java.awt.Color(255, 102, 255));

        jlbldescripcion.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jlbldescripcion.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblpieza)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlbldescripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jlblnompieza)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlblnompieza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbldescripcion)
                .addGap(53, 53, 53)
                .addComponent(jlblpieza)
                .addContainerGap(517, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("Placa Base");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("RAM");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de poder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Disco Duro (HDD)");
        jMenuItem9.setToolTipText("");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Unidad SSD");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Video (GPU)");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Tarjeta de Red");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Ventilador del Gabinete");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Tarjeta de Sonido");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Bateria CMOS");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Cable SATA");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Cable de Alimentación");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("BIOS/UEFI");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ayuda");

        jMenuItem19.setText("Acerca del Programa");
        jMenu4.add(jMenuItem19);

        jMenuItem20.setText("Creditos a: Federico Cotto IVC");
        jMenu4.add(jMenuItem20);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblnompieza.setText("");
        jlblnompieza.setText("Memoria RAM");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("es un módulo de almacenamiento temporal de alta velocidad y su función es guardar los datos de los programas activos para que el procesador acceda a ellos al instante");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ram.png")));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblnompieza.setText("");
        jlblnompieza.setText("Placa Madre");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("es la tarjeta de circuito principal de la computadora y su función es interconectar todos los componentes del sistema para que se comuniquen entre sí");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motherboard.png")));
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jlblnompieza.setText("");
        jlblnompieza.setText("Procesador");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("es el chip de silicio que actúa como el cerebro de la PC y su función es procesar los datos y ejecutar las instrucciones de todos los programas"); 
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cpu.png")));
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Cooler");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("es un sistema de refrigeración por aire o líquido y su función es disipar el calor generado por el procesador para evitar que se sobrecaliente");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooler.png")));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Fuente de poder");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("es el dispositivo que recibe la corriente de la pared y su función es transformarla en los voltajes adecuados para alimentar de energía limpia a todo el hardware"); 
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fuente.png")));
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Funcionalidad Guardar");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Funcionalidad Abrir");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int msg=JOptionPane.showConfirmDialog(this,"Desea salir del Sistema?");
        if (msg==0)
            System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Disco Duro HDD");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es un dispositivo de almacenamiento magnético tradicional de alta capacidad y su función es guardar de forma permanente el sistema operativo, los programas y todos tus archivos personales de manera económica.");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/discoduro.png")));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Unidad SSD");
        jlbldescripcion.setText("");
        
        jlbldescripcion.setText("Es un disco de almacenamiento de estado sólido que utiliza memoria flash sin partes móviles y su función es guardar datos ofreciendo velocidades de lectura y escritura muchísimo más rápidas que un HDD para acelerar el encendido del PC");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/unidadssd.png")));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Tarjeta Grafica (GPU)");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es una tarjeta de expansión dedicada al procesamiento de gráficos y su función es procesar y renderizar las imágenes, videos y entornos 3D para que se puedan mostrar en la pantalla");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gpu.png")));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Tarjeta de Red");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es una interfaz de hardware integrada o de expansión (Ethernet o Wi-Fi) y su función es permitir que la computadora se conecte a una red local y a Internet de forma inalámbrica o por cable");
       
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjetared.png")));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Ventilador de Gabinete");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es un ventilador auxiliar que se instala en el chasis de la PC y su función es retirar el aire caliente del interior e introducir aire fresco para mantener una temperatura segura en todo el sistema");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventiladordegabinete.png")));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Tarjeta de Sonido");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es un dispositivo de hardware encargado de procesar el audio y su función es convertir las señales digitales de la PC en sonidos analógicos para los parlantes y viceversa para el micrófono");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjetadesonido.png")));
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Bateria");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es una pequeña pila de botón ubicada en la placa base y su función es mantener energizado el chip CMOS para que no se borren la hora, la fecha y la configuración del sistema cuando la PC está apagada");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bateriaaaa.png")));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Cables SATA");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es un cable de conexión de datos plano y delgado y su función es conectar físicamente los discos duros y unidades SSD a la placa base para que puedan transferir la información");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SATA.png")));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("Cable de Alimentación");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es el cable eléctrico exterior que va al tomacorriente y su función es suministrar la corriente eléctrica necesaria desde la red de tu hogar hacia la fuente de poder de la PC");
        
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cabledealimentacion.png")));
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
         jlblnompieza.setText("");
        jlblnompieza.setText("BIOS/UEFI");
        jlbldescripcion.setText("");
        jlbldescripcion.setText("Es el primer programa o firmware grabado en un chip de la placa base y su función es iniciar y verificar que todo el hardware funcione correctamente antes de dar paso a la carga del sistema operativo");
        jlblpieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bios.png")));
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmEjercicioGA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmEjercicioGA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmEjercicioGA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmEjercicioGA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmEjercicioGA3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbldescripcion;
    private javax.swing.JLabel jlblnompieza;
    private javax.swing.JLabel jlblpieza;
    // End of variables declaration//GEN-END:variables
}
